// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQqOQXH84aE0XXJOIVegjvaMU2IQmCuI',
    appId: '1:1039310271276:android:d5414ae6626db985c27289',
    messagingSenderId: '1039310271276',
    projectId: 'pp191225-40959',
    storageBucket: 'pp191225-40959.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1LQXuL9Ad1iUSJ1TBLF864vAvo2W8mXU',
    appId: '1:1039310271276:ios:0d068562db2540c4c27289',
    messagingSenderId: '1039310271276',
    projectId: 'pp191225-40959',
    storageBucket: 'pp191225-40959.firebasestorage.app',
    androidClientId: '1039310271276-6icaf578n651dr6kqdgon9aoobptsq1r.apps.googleusercontent.com',
    iosClientId: '1039310271276-9vun8qrjprau7oc8aco2u1fe3fgdtp7a.apps.googleusercontent.com',
    iosBundleId: 'com.example.temp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvF-Vl0pHhB00Yau8-C6vPWH5ewgzz8UY',
    appId: '1:1039310271276:web:6673325e111a792bc27289',
    messagingSenderId: '1039310271276',
    projectId: 'pp191225-40959',
    authDomain: 'pp191225-40959.firebaseapp.com',
    storageBucket: 'pp191225-40959.firebasestorage.app',
  );
}
